### ISSUE TITLE
Graceful reboot

### ISSUE THREAD

**Issue by thebsdbox** [gianarb/noname#11]
Possibilities:

- Pass `pid:host` to `tink-docker` which may allow a `reboot` syscall to work.
- Some third container shenanigans that can signal to the OS. 
- ACPI call ... No clue how this would work.. sounds cool though.

**Comment by gianarb** [comment]
I like the idea to be as transparent as possible here, an API call or container shenanigans (maybe a remap) sounds magic.

If we can hide something around the reboot syscall I think that will be nice and transparent but I don't know a lot

**Comment by displague** [comment]
Can we bind mount /proc from the host and use `echo b > /proc/sysrq-trigger`? https://stackoverflow.com/a/24759427

**Comment by gianarb** [comment]
Thank you for your feedback @displague . Finding a way to "cut the power" for a server is easy as you wrote. For example, ContainerSolution uses `sysrq-trigger` here https://github.com/ContainerSolutions/tinkerbell-rpi4-workflow/blob/master/workflow/05-reboot/reboot.sh#L8 .

The real problem is how to make to catch the reboot and notify to tink-server that it actually happened. Otherwise, the action will be marked as a failure.

**Comment by thebsdbox** [comment]
We need a nice way of replying "we're now going to reboot" as we reboot. Just "resetting" doesn't answer the action so leaves it failed.

**Comment by deitch** [comment]
Is there any reason not to just pass `tink-docker` the necessary capabilities? If you look at the tests from linuxkit, they often include a poweroff, using docker.io/linuxkit/poweroff, e.g. [here](https://github.com/linuxkit/linuxkit/blob/master/test/cases/000_build/020_binds/test.yml#L18-L20).

That one already has `CAP_SYS_BOOT`, see [here](https://github.com/linuxkit/linuxkit/blob/master/test/pkg/poweroff/Dockerfile#L12)

**Comment by thebsdbox** [comment]
> Is there any reason not to just pass `tink-docker` the necessary capabilities? If you look at the tests from linuxkit, they often include a poweroff, using docker.io/linuxkit/poweroff, e.g. [here](https://github.com/linuxkit/linuxkit/blob/master/test/cases/000_build/020_binds/test.yml#L18-L20).
> 
> That one already has `CAP_SYS_BOOT`, see [here](https://github.com/linuxkit/linuxkit/blob/master/test/pkg/poweroff/Dockerfile#L12)

This is the plan ! 👍

**Comment by thebsdbox** [comment]
`pid:host` was all I needed! Can't wait to kill this issue :D

**Comment by thebsdbox** [comment]
This can be closed via #13 and demonstrated today.
